<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UserDetail.aspx.cs" Inherits="New_project.UserDetail" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>User Detail</title>
    <style type="text/css">

        .style2
        {
            font-size: x-large;
            font-family: "Segoe UI Light";
            font-weight: 700;
        }
        </style>
</head>
<body>
    <form id="form1" runat="server">
    <p>
    
            <span lang="en-us" style="font-size: large"><span lang="en-us">&nbsp;<asp:Image ID="Image1" 
                runat="server" Height="121px" ImageUrl="img/icon.jpg" 
            Width="140px" />
            <asp:Label 
                ID="Label26" runat="server" BorderStyle="None" BorderWidth="4px" 
                Font-Bold="True" Font-Size="50pt" Font-Underline="False" 
                Text="DCIS Defence Career Information System" Font-Names="Segoe UI Light" 
                style="font-size: xx-large"></asp:Label>
            </span>
            <asp:Panel ID="Panel1" runat="server" Height="36px" 
                style="color: #FFFFFF; background-color: #0099FF">
                <span class="style2">&nbsp;&nbsp; User Details<br />
                </span>
            </asp:Panel>
            <br />
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" 
        BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" 
        DataKeyNames="Username" DataSourceID="SqlDataSource1" ForeColor="Black" 
        GridLines="Vertical" HorizontalAlign="Center">
        <Columns>
            <asp:BoundField DataField="Fname" HeaderText="Fname" SortExpression="Fname" />
            <asp:BoundField DataField="Lname" HeaderText="Lname" SortExpression="Lname" />
            <asp:BoundField DataField="Username" HeaderText="Username" ReadOnly="True" 
                SortExpression="Username" />
            <asp:BoundField DataField="Password" HeaderText="Password" 
                SortExpression="Password" />
            <asp:BoundField DataField="Country" HeaderText="Country" 
                SortExpression="Country" />
            <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" />
            <asp:BoundField DataField="Gender" HeaderText="Gender" 
                SortExpression="Gender" />
            <asp:BoundField DataField="Country_Code" HeaderText="Country_Code" 
                SortExpression="Country_Code" />
            <asp:BoundField DataField="Phone_No" HeaderText="Phone_No" 
                SortExpression="Phone_No" />
            <asp:BoundField DataField="Alternative_Address" 
                HeaderText="Alternative_Address" SortExpression="Alternative_Address" />
            <asp:BoundField DataField="Adhaar_Card" HeaderText="Adhaar_Card" 
                SortExpression="Adhaar_Card" />
            <asp:BoundField DataField="Security_Question" HeaderText="Security_Question" 
                SortExpression="Security_Question" />
            <asp:BoundField DataField="Security_Answer" HeaderText="Security_Answer" 
                SortExpression="Security_Answer" />
        </Columns>
        <FooterStyle BackColor="#CCCCCC" />
        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
        <AlternatingRowStyle BackColor="#CCCCCC" />
    </asp:GridView>
    <br />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
        DeleteCommand="DELETE FROM [User_Table] WHERE [Username] = @Username" 
        InsertCommand="INSERT INTO [User_Table] ([Fname], [Lname], [Username], [Password], [Country], [DOB], [Gender], [Country_Code], [Phone_No], [Alternative_Address], [Adhaar_Card], [Security_Question], [Security_Answer]) VALUES (@Fname, @Lname, @Username, @Password, @Country, @DOB, @Gender, @Country_Code, @Phone_No, @Alternative_Address, @Adhaar_Card, @Security_Question, @Security_Answer)" 
        SelectCommand="SELECT * FROM [User_Table]" 
        UpdateCommand="UPDATE [User_Table] SET [Fname] = @Fname, [Lname] = @Lname, [Password] = @Password, [Country] = @Country, [DOB] = @DOB, [Gender] = @Gender, [Country_Code] = @Country_Code, [Phone_No] = @Phone_No, [Alternative_Address] = @Alternative_Address, [Adhaar_Card] = @Adhaar_Card, [Security_Question] = @Security_Question, [Security_Answer] = @Security_Answer WHERE [Username] = @Username">
        <DeleteParameters>
            <asp:Parameter Name="Username" Type="String" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="Fname" Type="String" />
            <asp:Parameter Name="Lname" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="Country" Type="String" />
            <asp:Parameter Name="DOB" Type="String" />
            <asp:Parameter Name="Gender" Type="String" />
            <asp:Parameter Name="Country_Code" Type="String" />
            <asp:Parameter Name="Phone_No" Type="String" />
            <asp:Parameter Name="Alternative_Address" Type="String" />
            <asp:Parameter Name="Adhaar_Card" Type="String" />
            <asp:Parameter Name="Security_Question" Type="String" />
            <asp:Parameter Name="Security_Answer" Type="String" />
            <asp:Parameter Name="Username" Type="String" />
        </UpdateParameters>
        <InsertParameters>
            <asp:Parameter Name="Fname" Type="String" />
            <asp:Parameter Name="Lname" Type="String" />
            <asp:Parameter Name="Username" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="Country" Type="String" />
            <asp:Parameter Name="DOB" Type="String" />
            <asp:Parameter Name="Gender" Type="String" />
            <asp:Parameter Name="Country_Code" Type="String" />
            <asp:Parameter Name="Phone_No" Type="String" />
            <asp:Parameter Name="Alternative_Address" Type="String" />
            <asp:Parameter Name="Adhaar_Card" Type="String" />
            <asp:Parameter Name="Security_Question" Type="String" />
            <asp:Parameter Name="Security_Answer" Type="String" />
        </InsertParameters>
    </asp:SqlDataSource>
    <br />
            </span>
    
    <div>
    
    </div>
    </form>
</body>
</html>
